import type { ManualFieldDef } from '@/types/case';

export const manualFieldRegistry: ManualFieldDef[] = [
  // ── 통합신청서 관련 ──
  {
    id: 'applicant_phone_kr',
    label: '연락처 (한국)',
    section: 'unified_app',
    fieldType: 'text',
    required: true,
    requiredForVisas: [],
    placeholder: '예: 010-1234-5678',
    halfWidth: true,
  },
  {
    id: 'entry_date',
    label: '입국 예정일',
    section: 'unified_app',
    fieldType: 'date',
    required: true,
    requiredForVisas: [],
    halfWidth: true,
  },
  {
    id: 'stay_duration',
    label: '체류 예정 기간',
    section: 'unified_app',
    fieldType: 'text',
    required: true,
    requiredForVisas: [],
    placeholder: '예: 1년, 6개월',
    halfWidth: true,
  },
  {
    id: 'annual_income',
    label: '연 소득금액 (만원)',
    section: 'unified_app',
    fieldType: 'text',
    required: false,
    requiredForVisas: [],
    placeholder: '예: 3600',
    halfWidth: true,
  },
  {
    id: 'refund_bank_account',
    label: '환불용 계좌번호',
    section: 'unified_app',
    fieldType: 'text',
    required: false,
    requiredForVisas: [],
    placeholder: '예: 국민은행 123-456-789012',
  },
  {
    id: 'cost_bearer',
    label: '체류비용 부담자',
    section: 'unified_app',
    fieldType: 'select',
    options: [
      { value: '본인', label: '본인' },
      { value: '초청인', label: '초청인(고용주)' },
      { value: '기타', label: '기타' },
    ],
    defaultValue: '초청인',
    required: false,
    requiredForVisas: [],
    halfWidth: true,
  },

  // ── 고용사유서 관련 ──
  {
    id: 'company_capital',
    label: '자본금 (백만원)',
    section: 'employment_reason',
    fieldType: 'text',
    required: true,
    requiredForVisas: ['E-7'],
    placeholder: '예: 500',
    halfWidth: true,
  },
  {
    id: 'company_revenue',
    label: '총매출액 (백만원)',
    section: 'employment_reason',
    fieldType: 'text',
    required: true,
    requiredForVisas: ['E-7'],
    placeholder: '예: 2000',
    halfWidth: true,
  },
  {
    id: 'company_debt',
    label: '부채총액 (백만원)',
    section: 'employment_reason',
    fieldType: 'text',
    required: false,
    requiredForVisas: ['E-7'],
    placeholder: '예: 300',
    halfWidth: true,
  },
  {
    id: 'company_profit',
    label: '영업이익 (백만원)',
    section: 'employment_reason',
    fieldType: 'text',
    required: false,
    requiredForVisas: ['E-7'],
    placeholder: '예: 150',
    halfWidth: true,
  },
  {
    id: 'employee_count',
    label: '상시종업원수',
    section: 'employment_reason',
    fieldType: 'text',
    required: true,
    requiredForVisas: ['E-7'],
    placeholder: '예: 45',
    halfWidth: true,
  },
  {
    id: 'foreign_expert_count',
    label: '현재 외국전문인력수',
    section: 'employment_reason',
    fieldType: 'text',
    required: true,
    requiredForVisas: ['E-7'],
    placeholder: '예: 3',
    halfWidth: true,
  },

  {
    id: 'company_description',
    label: '회사 및 사업(업무) 소개',
    section: 'employment_reason',
    fieldType: 'textarea',
    required: false,
    requiredForVisas: ['E-7'],
    placeholder: '회사 소개 및 주요 사업 내용을 입력하세요',
  },
  {
    id: 'career1_company',
    label: '경력1 - 업체명',
    section: 'employment_reason',
    fieldType: 'text',
    required: false,
    requiredForVisas: ['E-7'],
    placeholder: '예: ABC Corporation',
    halfWidth: true,
  },
  {
    id: 'career1_period',
    label: '경력1 - 재직기간',
    section: 'employment_reason',
    fieldType: 'text',
    required: false,
    requiredForVisas: ['E-7'],
    placeholder: '예: 2019.03~2022.06',
    halfWidth: true,
  },
  {
    id: 'career1_field',
    label: '경력1 - 근무분야',
    section: 'employment_reason',
    fieldType: 'text',
    required: false,
    requiredForVisas: ['E-7'],
    placeholder: '예: 소프트웨어 개발',
    halfWidth: true,
  },
  {
    id: 'career1_position',
    label: '경력1 - 직위',
    section: 'employment_reason',
    fieldType: 'text',
    required: false,
    requiredForVisas: ['E-7'],
    placeholder: '예: 시니어 개발자',
    halfWidth: true,
  },
  {
    id: 'career2_company',
    label: '경력2 - 업체명',
    section: 'employment_reason',
    fieldType: 'text',
    required: false,
    requiredForVisas: ['E-7'],
    placeholder: '예: XYZ Inc.',
    halfWidth: true,
  },
  {
    id: 'career2_period',
    label: '경력2 - 재직기간',
    section: 'employment_reason',
    fieldType: 'text',
    required: false,
    requiredForVisas: ['E-7'],
    placeholder: '예: 2022.07~2024.12',
    halfWidth: true,
  },
  {
    id: 'career2_field',
    label: '경력2 - 근무분야',
    section: 'employment_reason',
    fieldType: 'text',
    required: false,
    requiredForVisas: ['E-7'],
    placeholder: '예: 데이터 분석',
    halfWidth: true,
  },
  {
    id: 'career2_position',
    label: '경력2 - 직위',
    section: 'employment_reason',
    fieldType: 'text',
    required: false,
    requiredForVisas: ['E-7'],
    placeholder: '예: 팀장',
    halfWidth: true,
  },
  {
    id: 'er_reason',
    label: '고용사유',
    section: 'employment_reason',
    fieldType: 'textarea',
    required: false,
    requiredForVisas: ['E-7'],
    placeholder: '외국인 전문인력을 고용하려는 사유를 입력하세요',
  },
  {
    id: 'er_tech_effect',
    label: '기술도입 및 고용 효과',
    section: 'employment_reason',
    fieldType: 'textarea',
    required: false,
    requiredForVisas: ['E-7'],
    placeholder: '기술도입 및 고용 효과를 입력하세요',
  },
  {
    id: 'er_utilization_plan',
    label: '활용계획',
    section: 'employment_reason',
    fieldType: 'textarea',
    required: false,
    requiredForVisas: ['E-7'],
    placeholder: '인력 활용 계획을 입력하세요',
  },
  {
    id: 'er_other',
    label: '기타사항',
    section: 'employment_reason',
    fieldType: 'textarea',
    required: false,
    requiredForVisas: ['E-7'],
    placeholder: '기타사항을 입력하세요',
  },

  // ── 신원보증서 관련 ──
  {
    id: 'guarantor_name',
    label: '신원보증인 성명',
    section: 'guarantor',
    fieldType: 'text',
    required: true,
    requiredForVisas: ['E-7'],
    placeholder: '예: 김철수',
    halfWidth: true,
  },
  {
    id: 'guarantor_relation',
    label: '피보증인과의 관계',
    section: 'guarantor',
    fieldType: 'select',
    options: [
      { value: '고용주', label: '고용주' },
      { value: '친족', label: '친족' },
      { value: '지인', label: '지인' },
      { value: '기타', label: '기타' },
    ],
    required: true,
    requiredForVisas: ['E-7'],
    halfWidth: true,
  },
  {
    id: 'guarantor_position',
    label: '보증인 직위',
    section: 'guarantor',
    fieldType: 'text',
    required: true,
    requiredForVisas: ['E-7'],
    placeholder: '예: 대표이사',
    halfWidth: true,
  },
  {
    id: 'guarantor_phone',
    label: '보증인 연락처',
    section: 'guarantor',
    fieldType: 'text',
    required: false,
    requiredForVisas: ['E-7'],
    placeholder: '예: 02-1234-5678',
    halfWidth: true,
  },

  // ── 거주숙소 확인서 관련 ──
  {
    id: 'landlord_name',
    label: '숙소 제공자 성명',
    section: 'residence',
    fieldType: 'text',
    required: true,
    requiredForVisas: ['E-7'],
    placeholder: '예: 박영희 / (주)테크솔루션',
    halfWidth: true,
  },
  {
    id: 'landlord_nationality',
    label: '숙소 제공자 국적',
    section: 'residence',
    fieldType: 'text',
    required: false,
    requiredForVisas: ['E-7'],
    placeholder: '예: 대한민국',
    halfWidth: true,
  },
  {
    id: 'landlord_relation',
    label: '외국인과의 관계',
    section: 'residence',
    fieldType: 'select',
    options: [
      { value: '친족', label: '친족' },
      { value: '고용주', label: '고용주' },
      { value: '기타', label: '기타' },
    ],
    required: true,
    requiredForVisas: ['E-7'],
    halfWidth: true,
  },
  {
    id: 'ownership_type',
    label: '소유형태',
    section: 'residence',
    fieldType: 'select',
    options: [
      { value: '자가', label: '자가' },
      { value: '임대', label: '임대' },
      { value: '기타', label: '기타' },
    ],
    required: true,
    requiredForVisas: ['E-7'],
    halfWidth: true,
  },
  {
    id: 'residence_type',
    label: '주거형태',
    section: 'residence',
    fieldType: 'select',
    options: [
      { value: '개인주택 등', label: '개인주택 등' },
      { value: '기숙사', label: '기숙사' },
      { value: '숙박시설', label: '숙박시설' },
      { value: '기타', label: '기타' },
    ],
    required: true,
    requiredForVisas: ['E-7'],
    halfWidth: true,
  },
  {
    id: 'residence_start_date',
    label: '숙소 제공 시작일',
    section: 'residence',
    fieldType: 'date',
    required: false,
    requiredForVisas: ['E-7'],
    halfWidth: true,
  },

  // ── 신원보증서 추가 ──
  {
    id: 'guarantee_period',
    label: '보증기간',
    section: 'guarantor',
    fieldType: 'text',
    required: false,
    requiredForVisas: ['E-7'],
    placeholder: '예: 1년',
    halfWidth: true,
  },

  // ── 거주숙소 확인서 추가 ──
  {
    id: 'landlord_phone',
    label: '숙소 제공자 연락처',
    section: 'residence',
    fieldType: 'text',
    required: false,
    requiredForVisas: ['E-7'],
    placeholder: '예: 02-1234-5678',
    halfWidth: true,
  },

  // ── 외국인 직업신고서 ──
  {
    id: 'occupation_category',
    label: '직업 분류',
    section: 'occupation_report',
    fieldType: 'select',
    options: [
      { value: '관리자', label: '관리자' },
      { value: '경영·회계·사무 관련직', label: '경영·회계·사무 관련직' },
      { value: '금융·보험 관련직', label: '금융·보험 관련직' },
      { value: '교육 및 자연과학·사회과학 연구 관련직', label: '교육 및 자연과학·사회과학 연구 관련직' },
      { value: '법률·경찰·소방·교도 관련직', label: '법률·경찰·소방·교도 관련직' },
      { value: '보건·의료 관련직', label: '보건·의료 관련직' },
      { value: '사회복지 및 종교 관련직', label: '사회복지 및 종교 관련직' },
      { value: '문화·예술·디자인·방송 관련직', label: '문화·예술·디자인·방송 관련직' },
      { value: '운전 및 운송 관련직', label: '운전 및 운송 관련직' },
      { value: '영업 및 판매 관련직', label: '영업 및 판매 관련직' },
      { value: '경비 및 청소 관련직', label: '경비 및 청소 관련직' },
      { value: '미용·숙박·여행·오락·스포츠 관련직', label: '미용·숙박·여행·오락·스포츠 관련직' },
      { value: '음식서비스 관련직', label: '음식서비스 관련직' },
      { value: '건설 관련직', label: '건설 관련직' },
      { value: '기계 관련직', label: '기계 관련직' },
      { value: '재료 관련직', label: '재료 관련직' },
      { value: '화학 관련직', label: '화학 관련직' },
      { value: '섬유·의복 관련직', label: '섬유·의복 관련직' },
      { value: '전기·전자 관련직', label: '전기·전자 관련직' },
      { value: '정보통신 관련직', label: '정보통신 관련직' },
      { value: '식품가공 관련직', label: '식품가공 관련직' },
      { value: '인쇄·목재·가구·공예 및 기타 설치·정비·생산직', label: '인쇄·목재·가구·공예 및 기타 설치·정비·생산직' },
      { value: '농림어업 관련직', label: '농림어업 관련직' },
      { value: '군인', label: '군인' },
      { value: '의회의원·고위공무원 및 공공단체임원', label: '의회의원·고위공무원 및 공공단체임원' },
      { value: '기업고위임원', label: '기업고위임원' },
      { value: '경영지원관리자', label: '경영지원관리자' },
      { value: '기타 관리자', label: '기타 관리자' },
      { value: '경영 관련 사무직', label: '경영 관련 사무직' },
      { value: '회계·세무 관련 사무직', label: '회계·세무 관련 사무직' },
      { value: '비서 및 사무보조', label: '비서 및 사무보조' },
      { value: '상담·안내·통계·감사 사무직', label: '상담·안내·통계·감사 사무직' },
      { value: '금융 및 보험 관련 사무직', label: '금융 및 보험 관련 사무직' },
      { value: '무역·운송 사무직', label: '무역·운송 사무직' },
      { value: '자연과학 관련 전문가', label: '자연과학 관련 전문가' },
      { value: '인문·사회과학 관련 전문가', label: '인문·사회과학 관련 전문가' },
      { value: '생명과학 관련 전문가', label: '생명과학 관련 전문가' },
      { value: '정보통신 관련 전문가 및 기술직', label: '정보통신 관련 전문가 및 기술직' },
      { value: '공학 관련 전문가 및 기술직', label: '공학 관련 전문가 및 기술직' },
      { value: '보건·의료 관련 전문가', label: '보건·의료 관련 전문가' },
      { value: '교육 관련 전문가', label: '교육 관련 전문가' },
      { value: '법률 관련 전문가', label: '법률 관련 전문가' },
      { value: '행정 관련 전문가', label: '행정 관련 전문가' },
      { value: '경영·금융 관련 전문가', label: '경영·금융 관련 전문가' },
      { value: '문화·예술 관련 전문가', label: '문화·예술 관련 전문가' },
      { value: '방송·언론 관련 전문가', label: '방송·언론 관련 전문가' },
      { value: '사회서비스 관련 전문가', label: '사회서비스 관련 전문가' },
      { value: '경찰·소방·보안 관련 전문가', label: '경찰·소방·보안 관련 전문가' },
      { value: '스포츠·레크리에이션 관련 전문가', label: '스포츠·레크리에이션 관련 전문가' },
      { value: '식품가공 관련 전문가', label: '식품가공 관련 전문가' },
      { value: '환경·에너지 관련 전문가', label: '환경·에너지 관련 전문가' },
      { value: '군사 관련 전문가', label: '군사 관련 전문가' },
    ],
    required: false,
    requiredForVisas: ['E-7', 'F-2'],
  },

  // ── 기타 ──
  {
    id: 'criminal_record',
    label: '범죄경력',
    section: 'other',
    fieldType: 'radio',
    options: [
      { value: '예', label: '예' },
      { value: '아니오', label: '아니오' },
    ],
    defaultValue: '아니오',
    required: false,
    requiredForVisas: [],
    halfWidth: true,
  },
  {
    id: 'deportation_history',
    label: '강제퇴거/출국명령 이력',
    section: 'other',
    fieldType: 'radio',
    options: [
      { value: '예', label: '예' },
      { value: '아니오', label: '아니오' },
    ],
    defaultValue: '아니오',
    required: false,
    requiredForVisas: [],
    halfWidth: true,
  },
  {
    id: 'previous_visit',
    label: '이전 한국 방문 이력',
    section: 'other',
    fieldType: 'radio',
    options: [
      { value: '예', label: '예' },
      { value: '아니오', label: '아니오' },
    ],
    defaultValue: '아니오',
    required: false,
    requiredForVisas: [],
    halfWidth: true,
  },
  {
    id: 'stay_experience',
    label: '한국 내 체류 경험',
    section: 'other',
    fieldType: 'radio',
    options: [
      { value: '예', label: '예' },
      { value: '아니오', label: '아니오' },
    ],
    defaultValue: '아니오',
    required: false,
    requiredForVisas: [],
    halfWidth: true,
  },
];

export const sectionMeta: Record<
  ManualFieldDef['section'],
  { label: string; defaultOpen: boolean; visaFilter?: string[]; badge?: string }
> = {
  unified_app: {
    label: '통합신청서',
    defaultOpen: true,
  },
  employment_reason: {
    label: '고용사유서',
    defaultOpen: true,
    visaFilter: ['E-7'],
  },
  guarantor: {
    label: '신원보증서',
    defaultOpen: true,
    visaFilter: ['E-7'],
  },
  residence: {
    label: '거주숙소 확인서',
    defaultOpen: true,
    visaFilter: ['E-7'],
  },
  occupation_report: {
    label: '외국인 직업신고서',
    defaultOpen: true,
    visaFilter: ['E-7', 'F-2'],
  },
  other: {
    label: '기타',
    defaultOpen: false,
    badge: '기본값 자동 설정됨',
  },
};

export const sectionOrder: ManualFieldDef['section'][] = [
  'unified_app',
  'employment_reason',
  'guarantor',
  'residence',
  'occupation_report',
  'other',
];

export function getFieldsForVisa(visaType: string): ManualFieldDef[] {
  return manualFieldRegistry.filter(
    (f) => f.requiredForVisas.length === 0 || f.requiredForVisas.includes(visaType)
  );
}

export function getDefaultValues(visaType: string): Record<string, string> {
  const defaults: Record<string, string> = {};
  for (const field of getFieldsForVisa(visaType)) {
    if (field.defaultValue) {
      defaults[field.id] = field.defaultValue;
    }
  }
  return defaults;
}
